//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuegoAhorcado.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JuegoAhorcado.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0 {
            get {
                object obj = ResourceManager.GetObject("0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1 {
            get {
                object obj = ResourceManager.GetObject("1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2 {
            get {
                object obj = ResourceManager.GetObject("2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3 {
            get {
                object obj = ResourceManager.GetObject("3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4 {
            get {
                object obj = ResourceManager.GetObject("4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aachen/M
        ///aardvark/MS
        ///aardwolf
        ///aardwolves
        ///aargh
        ///Aarhus/M
        ///Aaron/M
        ///Aaronvitch/M
        ///Ababa/M
        ///aback
        ///abacus/SM
        ///abaft
        ///abalone/MS
        ///abandon/LdS
        ///abandoner/M
        ///abandonware
        ///abase/SGLD
        ///abaser/M
        ///abash/LGhSD
        ///abashed/UY
        ///abate/DLGS
        ///abated/U
        ///abater/M
        ///abattoir/SM
        ///Abba/M
        ///abbess/SM
        ///abbey/SM
        ///abbot/SM
        ///Abbott/M
        ///abbreviate/NDnSG
        ///abbreviated/U
        ///abbreviation/M
        ///abbé/S
        ///ABC/S
        ///abdicate/DNGSn
        ///abdication/M
        ///abdomen/MS
        ///abdominal/YS
        ///abduct/SDG
        ///abductee/S
        ///abduction/SM
        ///abductor/MS
        ///Abdul/M
        ///Abdullah
        ///Abe/M
        ///abea [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a abaco/OTqr
        ///Abacuc
        ///abadessa/QTUqrs
        ///abalietà/TU
        ///abanese/STUqrs
        ///Abano/Tqr
        ///abarica/QTU
        ///abarico/OT
        ///abasia/QTU
        ///abate/STqr
        ///abatino/OTqr
        ///abatterica/QTU
        ///abatterico/nYT
        ///abazia/QTUq
        ///abbacchiamento/OTq
        ///abbacchiando/D
        ///abbacchiare/ALKhlTXI
        ///abbacchiata/QTU
        ///abbacchiato/EyT
        ///abbacchiatura/QTUqs
        ///abbacchio/OTq
        ///abbacinamento/OTq
        ///abbacinando/D
        ///abbacinare/ALKhlTXI
        ///abbacinata/QTU
        ///abbacinato/EyT
        ///abbadia/QTUqrs
        ///abbadinga/QTUqrs
        ///abbadingo/OTqr
        ///Abbado/Tqr
        ///abbagliamento/OTq
        ///abbagliando/D
        ///abbagliante/STUq
        ///abbagliare/ALKhlTXI
        ///abbagliata/ [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Italian {
            get {
                return ResourceManager.GetString("Italian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a a
        ///ababa/S
        ///ababillar/RED
        ///ababol/S
        ///abacería/S
        ///abacero/GS
        ///ábaco/S
        ///Abad
        ///abada/S
        ///abadejo/S
        ///abadengo/GS
        ///abadengo/S
        ///abadernar/RED
        ///abadesa/S
        ///Abadía
        ///abadía/S
        ///abadiato/S
        ///abad/S
        ///abajadero/S
        ///abajamiento/S
        ///abajar/RED
        ///abajeño/GS
        ///abajo
        ///Abajo
        ///Abalá
        ///abalanzar/REDÁÅñòø
        ///abalar/RED
        ///abaldonar
        ///abalear/RED
        ///abalizar/RED
        ///aballar/RED
        ///aballestar/RED
        ///abalorio/S
        ///abaluartar/RED
        ///abanar/RED
        ///abancalar/RED
        ///Abancay
        ///abanderado/GS
        ///abanderamiento/S
        ///abanderar/RED
        ///abanderizar/RED
        ///abandonadamente
        ///abandonado/GS
        ///abandonar/REDÀÁÂÄÅÆÌñòô
        ///abandonismo/S [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
    }
}
